[project]
authors = ["Sukuna"]
entry = "main.sw"
license = "Apache-2.0"
name = "petition-contract"

[dependencies]

[toolchain]
channel = "latest-2023-07-18"

[components]
forc = "0.60.0"
fuel-core = "0.27.0"



